use customer_behavior;
-- show all records.
select * from mytable limit 10;

-- ques 1. what is the total revenue generated by male v/s female customers.
select gender,sum(purchase_amount) as revenue
from mytable
group by gender;

-- ques2. which customers used a discount but still spent more than the average purchase amount.
select customer_id, purchase_amount
from mytable
where discount_applied='yes' and purchase_amount >=(select AVG(purchase_amount) from mytable);

-- ques 3.. which are the top five products with the highest average review rating.
select item_purchased,ROUND(AVG(review_rating),2) as "Average Product Rating"
from mytable
group by item_purchased
order by avg(review_rating)desc
limit 5;

-- ques 4.  compare the average purchase amount between standard and express shipping.
select shipping_type,ROUND(AVG(purchase_amount),2) from mytable
where shipping_type in ('standard','Express')
group by shipping_type ;

-- ques5. Do subscribed customers spend more? compare average spend and total revenue between
-- subscribers and non- subscribers.
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from mytable
group by subscription_status
order by total_revenue,avg_spend desc;

-- ques6. which five products have the highest percentage of purchases with discounts applied.
select item_purchased,
 ROUND(100 * SUM(CASE WHEN discount_applied='yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from mytable
group by item_purchased 
order by discount_rate desc
limit 5;

-- ques7. segment customer into new, returning and loyal based on their total 
-- number of previous purchases, and show the count of each segment.
with customer_type as(
select customer_id, previous_purchases,
case when previous_purchases=1 then 'new'
when previous_purchases between 2 and 10 then 'returning'
else 'loyal'
end as customer_segment
from mytable
)
select customer_segment, count(*) as 'number of customers'
from customer_type
group by customer_segment;

-- ques 8. what are the top 3 most purchased products within each category.

with item_counts as(
select category ,item_purchased, count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id)desc)as item_rank
from mytable
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3;

-- ques 9.. are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe.
select subscription_status, COUNT(customer_id) as repeat_buyers
from mytable
where previous_purchases > 5
group by subscription_status;

-- ques 10.. what is the revenue contribution of each age group. 
select age_group, sum(purchase_amount) as total_revenue
from mytable
group by age_group
order by total_revenue desc;
